# Generated by Django 6.0.3 on 2026-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ects_totais", models.IntegerField(default=180)),
                ("link_site", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "numero",
                    models.CharField(help_text="Número de docente", max_length=20),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("link_lusofona", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
