# Generated by Django 6.0.3 on 2026-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("link_oficial", models.URLField()),
                ("detalhes", models.TextField()),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
            ],
        ),
    ]
