# Generated by Django 6.0.3 on 2026-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("Soft", "Soft Skill"), ("Hard", "Hard Skill")],
                        max_length=10,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("Iniciante", "Iniciante"),
                            ("Intermédio", "Intermédio"),
                            ("Avançado", "Avançado"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designacao", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField()),
                (
                    "competencias_adquiridas",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
    ]
