# Generated by Django 6.0.3 on 2026-04-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_competencia_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True, null=True)),
                ("link_github", models.URLField(blank=True, null=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
