# Generated by Django 6.0.3 on 2026-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autores", models.CharField(max_length=300)),
                ("resumo", models.TextField()),
                ("ano", models.IntegerField(default=2025)),
                ("link_documento", models.URLField(blank=True, null=True)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
    ]
