# Generated by Django 6.0.3 on 2026-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "entidade_relacionada",
                    models.CharField(
                        choices=[
                            ("Licenciatura", "Licenciatura"),
                            ("UnidadeCurricular", "Unidade Curricular"),
                            ("Projeto", "Projeto"),
                            ("Tecnologia", "Tecnologia"),
                            ("Competencia", "Competência"),
                            ("Formacao", "Formação"),
                            ("TFC", "TFC"),
                            ("Geral", "Geral / Arquitetura do Projeto"),
                        ],
                        default="Geral",
                        max_length=50,
                    ),
                ),
                (
                    "fotografia_caderno",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("descricao_decisoes", models.TextField(blank=True)),
                ("justificacao_modelacao", models.TextField(blank=True)),
                ("erros_correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("data_registo", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["data_registo"],
            },
        ),
    ]
