# Generated by Django 6.0.3 on 2026-04-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_makingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
