# Generated by Django 6.0.3 on 2026-04-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
