# Generated by Django 6.0.4 on 2026-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_unidadecurricular_semestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=200),
        ),
    ]
