# Generated by Django 6.0.4 on 2026-04-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipo",
            ),
        ),
    ]
