# Generated by Django 6.0.4 on 2026-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="Link para o perfil do LinkedIn ou da página da Lusófona",
                        null=True,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="professores/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
